import React from 'react';
import {
    AbsoluteFill, useCurrentFrame, Audio, staticFile, useVideoConfig,
} from 'remotion';
import { useAudioData, visualizeAudio } from '@remotion/media-utils';

// ── Lyrics format ────────────────────────────────────────────────────────────
// Each segment has start/end time (seconds) and text
export interface LyricSegment {
    start: number;
    end: number;
    text: string;
}

// Import lyrics JSON (generated by Whisper)
// Falls back to placeholder lyrics if file not present
let LYRICS: LyricSegment[] = [];
try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    LYRICS = require('../../../public/lyrics.json') as LyricSegment[];
} catch {
    LYRICS = [
        { start: 0, end: 3, text: 'PHONK' },
        { start: 3, end: 6, text: 'DROP IT' },
        { start: 6, end: 9, text: 'LET\'S GO' },
        { start: 9, end: 12, text: 'FEEL THE BEAT' },
        { start: 12, end: 15, text: 'RIDE THE WAVE' },
    ];
}

// ── Letter component ──────────────────────────────────────────────────────────
// Each letter can scatter (fly to a random offset) and reassemble
interface LetterProps {
    char: string;
    index: number;
    total: number;
    scatter: number; // 0 = assembled, 1 = fully scattered
    progress: number; // 0→1 entrance, 1 = fully visible, leaving: >1
    hue: number;
    volume: number;
    fontSize: number;
}

// Seeded "random" from index
const pseudoRnd = (seed: number) => ((seed * 9301 + 49297) % 233280) / 233280;

const LetterSpan: React.FC<LetterProps> = ({
    char, index, total, scatter, progress, hue, volume, fontSize,
}) => {
    if (char === ' ') return <span style={{ display: 'inline-block', width: fontSize * 0.3 }} />;

    const rndX = (pseudoRnd(index * 7 + 1) - 0.5) * 800;
    const rndY = (pseudoRnd(index * 7 + 2) - 0.5) * 1400;
    const rndR = (pseudoRnd(index * 7 + 3) - 0.5) * 720;

    const tx = rndX * scatter;
    const ty = rndY * scatter;
    const rot = rndR * scatter;
    const opacity = Math.max(0, 1 - scatter * 0.8);

    // Entrance: letters fly up from bottom sequentially
    const delay = (index / Math.max(total, 1)) * 0.4;
    const entranceP = Math.max(0, Math.min(1, (progress - delay) / 0.6));
    const entryY = entranceP < 1 ? (1 - entranceP) * 120 : 0;
    const entryOp = entranceP;

    // Beat pulse
    const pulse = 1 + volume * 0.18;

    const glowColor = `hsl(${hue + index * 8}, 100%, 70%)`;

    return (
        <span style={{
            display: 'inline-block',
            transform: `translate(${tx}px, ${ty + entryY}px) rotate(${rot}deg) scale(${pulse})`,
            opacity: opacity * entryOp,
            color: `hsl(${hue + index * 10}, 100%, 65%)`,
            textShadow: `
        0 0 ${10 + volume * 30}px ${glowColor},
        0 0 ${4 + volume * 12}px #fff
      `,
            transition: 'none',
            fontWeight: 900,
            letterSpacing: '-0.02em',
        }}>
            {char}
        </span>
    );
};

// ── Main composition ──────────────────────────────────────────────────────────
export const KineticText: React.FC = () => {
    const frame = useCurrentFrame();
    const { fps } = useVideoConfig();
    const audioUrl = staticFile('track.mp3');
    const audioData = useAudioData(audioUrl);

    if (!audioData) return <AbsoluteFill style={{ backgroundColor: '#000' }} />;

    const viz = visualizeAudio({ fps, frame, audioData, numberOfSamples: 64 });
    const bass = (viz[0] + viz[1] + viz[2]) / 3;
    const mid = (viz[5] + viz[6] + viz[7]) / 3;
    const volume = Math.min(bass * 3, 1);
    const isBeat = bass > 0.28;

    const currentSec = frame / fps;

    // Find active lyric segment
    const activeIdx = LYRICS.findIndex(
        (s) => currentSec >= s.start && currentSec < s.end,
    );
    const activeSeg = activeIdx >= 0 ? LYRICS[activeIdx] : null;


    // Beat scatter: letters scatter on beat, regroup between beats
    const scatter = isBeat ? Math.min(bass * 1.2, 0.12) : 0;

    // Hue rotates slowly
    const hue = (frame * 0.4 + mid * 80) % 360;

    const renderLine = (seg: LyricSegment, opacity: number, yOffset: number) => {
        const segDuration = seg.end - seg.start;
        const segProgress = Math.max(0, Math.min(1, (currentSec - seg.start) / Math.min(segDuration, 1)));
        const exitProgress = Math.max(0, (currentSec - (seg.end - 0.5)) / 0.5);
        const chars = seg.text.toUpperCase().split('');

        // Font size based on text length
        const fontSize = Math.min(180, Math.max(72, 1080 / Math.max(chars.length, 4) * 1.4));

        return (
            <div
                style={{
                    position: 'absolute',
                    left: 0, right: 0,
                    top: '50%',
                    transform: `translateY(calc(-50% + ${yOffset}px))
                      scale(${1 - exitProgress * 0.15})`,
                    opacity: opacity * (1 - exitProgress),
                    display: 'flex',
                    justifyContent: 'center',
                    alignItems: 'center',
                    flexWrap: 'wrap',
                    padding: '0 40px',
                    textAlign: 'center',
                    fontFamily: '"Impact", "Arial Black", sans-serif',
                    fontSize,
                    lineHeight: 1.0,
                    gap: 0,
                }}
            >
                {chars.map((ch, i) => (
                    <LetterSpan
                        key={i}
                        char={ch}
                        index={i}
                        total={chars.length}
                        scatter={scatter}
                        progress={segProgress}
                        hue={hue}
                        volume={volume}
                        fontSize={fontSize}
                    />
                ))}
            </div>
        );
    };

    // Background waveform
    const bars = Array.from({ length: 48 }, (_, i) => viz[i] ?? 0);

    return (
        <AbsoluteFill style={{ backgroundColor: '#000', overflow: 'hidden' }}>
            <Audio src={audioUrl} />

            {/* BG gradient */}
            <AbsoluteFill style={{
                background: `radial-gradient(ellipse at 50% 50%,
          rgba(${isBeat ? '80,0,160' : '20,0,60'},${0.6 + volume * 0.3}) 0%,
          rgba(0,0,0,1) 70%)`,
            }} />

            {/* Waveform bars behind text */}
            <div style={{
                position: 'absolute', bottom: 0, left: 0, right: 0,
                height: '30%', display: 'flex', alignItems: 'flex-end', gap: 2,
                opacity: 0.35,
            }}>
                {bars.map((amp, i) => {
                    const h = (i / bars.length) * 260 + 200;
                    return (
                        <div key={i} style={{
                            flex: 1,
                            height: `${amp * 3 * 100}%`,
                            background: `hsl(${h},100%,55%)`,
                        }} />
                    );
                })}
            </div>

            {/* LYRICS */}
            {activeSeg && renderLine(activeSeg, 1, 0)}

            {/* BEAT FLASH */}
            {isBeat && (
                <AbsoluteFill style={{
                    background: `rgba(${hue > 180 ? '0,100,255' : '200,0,255'},${bass * 0.12})`,
                    pointerEvents: 'none',
                }} />
            )}

            {/* SCANLINES */}
            <AbsoluteFill style={{
                backgroundImage: 'repeating-linear-gradient(0deg, transparent, transparent 3px, rgba(0,0,0,0.1) 4px)',
                pointerEvents: 'none',
            }} />

            {/* NO LYRICS placeholder */}
            {!activeSeg && LYRICS.length > 0 && (
                <div style={{
                    position: 'absolute', bottom: '35%', left: 0, right: 0,
                    textAlign: 'center', color: 'rgba(255,255,255,0.15)',
                    fontFamily: 'monospace', fontSize: 28,
                }}>
                    ♫
                </div>
            )}
        </AbsoluteFill>
    );
};
